[tox]
# Remember to add to .github/workflows/build.yml if this is added to.
envlist =
    # Not every combination, just a representative sample:
    py310-django{32,42}-test,
    py311-django{42,50}-test,
    py312-django{50,51,52}-test,
    checkmanifest-py310,

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
runner = uv-venv-runner
with_dev = true
commands =
    test: pytest --cov=mailer
    checkmanifest: check-manifest
deps = .
    checkmanifest: check-manifest
    django32: Django==3.2.4
    django42: Django==4.2.2
    django50: Django==5.0.14
    django51: Django==5.1.14
    django52: Django==5.2.8
