# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_messagelog_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
