# Generated by Django 5.0.4 on 2024-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0006_message_retry_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelog",
            name="message_data",
            field=models.TextField(null=True),
        ),
    ]
