# Generated by Django 3.2.16 on 2022-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_auto_20210204_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'low'), (4, 'deferred')]),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='when_added',
            field=models.DateTimeField(),
        ),
    ]
